# This file can be used to create a conda environment using:
# $ conda env create -f conda_cgb_environment.yml
# platform: linux-64
name: cgb3
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - numpy=1.20.3
  - scipy=1.6.3
  - matplotlib=3.4.2
  - pyparsing=2.4.7
  - biopython=1.79
  - pyzmq=19.0.2
  - ipython=7.26.0
  - spyder=5.1.1
  - lxml=4.6.3
  - pyqt=5.9.2
  - networkx=2.6.2
  - cached-property=1.5.2
  - pip
  - pip:
    # works for regular pip packages
    - ete3==3.1.2
    - tqdm==4.62.2
    - weblogo==3.7.8

